services:
  sylabackend:
    build:
      context: .
      dockerfile: Dockerfile
    image: syla-backend
    container_name: syla-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      DATABASE_URL: ${DATABASE_LOCAL_URL}
      DATABASE_LOCAL_URL: ${DATABASE_LOCAL_URL}
      DATABASE_PROD_URL: ${DATABASE_PROD_URL}
    volumes:
      - ./uploads:/app/uploads:delegated
      - ./app:/app/app:cached
    depends_on:
      - syla-db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  syla-db:
    image: postgres:16
    container_name: syla-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
