# fly.toml - Fly.io Configuration for Syla Analytics

app = "syla-backend"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  ENVIRONMENT = "production"
  PYTHONUNBUFFERED = "1"
  AI_ENABLED = "true"
  AI_DEFAULT_MODEL = "gpt-4o-mini"
  AI_TIMEOUT_SECONDS = "30"
  AI_RATE_LIMIT_PER_HOUR = "50"
  SMTP_ENABLED = "false"
  # Use internal Postgres connection
  DATABASE_URL = "postgresql://postgres:35oeE5MSmui4vUO@syla-db.internal:5432/syla_db?sslmode=disable"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "GET"
    path = "/api/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[mounts]]
  source = "syla_data"
  destination = "/app/uploads"
