services:
  - type: web
    name: syla-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker -w 4 -b 0.0.0.0:10000 app.main:app
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
