// frontend/src/components/ChartSummaryReport.jsx

import React from 'react';
import { Download, FileText } from 'lucide-react';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

export default function ChartSummaryReport({ summary = {}, data = [], chartTitle = "" }) {
  
  const formatNumber = (value) => {
    if (typeof value !== 'number') return value;
    if (Number.isInteger(value)) {
      return value.toLocaleString();
    }
    return value.toLocaleString(undefined, {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    });
  };
  
  const exportPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Header
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(255, 255, 255);
    doc.text('Data Summary Report', pageWidth / 2, 25, { align: 'center' });
    
    // Date & Time
    doc.setFontSize(9);
    doc.setTextColor(220, 220, 220);
    const now = new Date();
    doc.text(
      `${now.toLocaleDateString()} ${now.toLocaleTimeString()}`,
      pageWidth / 2,
      33,
      { align: 'center' }
    );
    
    doc.setTextColor(40, 40, 40);
    
    // Summary
    let yPos = 50;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(37, 99, 235);
    doc.text('Overview', 14, yPos);
    yPos += 8;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);
    const summaryText = `This report contains statistical analysis of ${data.length} data points across ${Object.keys(summary).length} columns. The data shows various metrics including numerical summaries and categorical breakdowns.`;
    const splitText = doc.splitTextToSize(summaryText, pageWidth - 28);
    doc.text(splitText, 14, yPos);
    yPos += splitText.length * 5 + 15;
    
    // Table
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(37, 99, 235);
    doc.text('Detailed Statistics', 14, yPos);
    yPos += 10;
    
    const tableData = [];
    Object.entries(summary).forEach(([col, details]) => {
      if (details && typeof details === 'object') {
        Object.entries(details).forEach(([key, value]) => {
          tableData.push([col, key, formatNumber(value)]);
        });
      } else {
        tableData.push([col, 'Value', formatNumber(details)]);
      }
    });
    
    doc.autoTable({
      startY: yPos,
      head: [['Column', 'Metric', 'Value']],
      body: tableData,
      theme: 'striped',
      headStyles: {
        fillColor: [37, 99, 235],
        fontSize: 11,
        fontStyle: 'bold',
        halign: 'center'
      },
      styles: {
        fontSize: 9,
        cellPadding: 4
      },
      alternateRowStyles: {
        fillColor: [245, 247, 250]
      },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 50 },
        1: { cellWidth: 60 },
        2: { halign: 'right', cellWidth: 'auto' }
      }
    });
    
    // Conclusion
    const finalY = doc.lastAutoTable.finalY + 15;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(37, 99, 235);
    doc.text('Conclusion & Next Steps', 14, finalY);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);
    const conclusion = doc.splitTextToSize(
      'This summary provides a snapshot of your data. For deeper insights and predictive analytics, consider using our AI Forecasting feature to project future trends and scenarios.',
      pageWidth - 28
    );
    doc.text(conclusion, 14, finalY + 8);
    
    // Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text(
      'Generated by Syla Analytics â€¢ © 2025 â€¢ Visit sylaanalytics.com',
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    
    doc.save(`summary-report-${chartTitle.replace(/\s+/g, '-') || 'data'}-${new Date().toISOString().split('T')[0]}.pdf`);
  };
  
  return (
    <div className="mt-6 rounded-2xl bg-white border border-gray-200 shadow-lg dark:bg-slate-900 dark:border-slate-700 overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-600 to-indigo-600 p-5 text-white flex items-center justify-between">
        <div className="flex items-center gap-3">
          <FileText size={24} />
          <div>
            <h2 className="text-xl font-bold">Data Summary</h2>
            <p className="text-sm text-blue-100">Statistical overview of your data</p>
          </div>
        </div>
        <button
          onClick={exportPDF}
          className="flex items-center gap-2 px-4 py-2 bg-white/20 hover:bg-white/30 backdrop-blur-sm rounded-lg font-medium transition-all shadow-lg hover:shadow-xl"
        >
          <Download size={18} />
          Export PDF
        </button>
      </div>
      
      {/* Table */}
      <div className="p-5 overflow-x-auto">
        <table className="min-w-full border-collapse">
          <thead>
            <tr className="bg-gradient-to-r from-blue-50 to-indigo-50 dark:from-blue-900/20 dark:to-indigo-900/20 border-b-2 border-blue-200 dark:border-blue-700">
            <th className="px-6 py-4 text-left text-sm font-bold text-gray-700 dark:text-slate-200 uppercase tracking-wider">
                Column
              </th>
              <th className="px-6 py-4 text-left text-sm font-bold text-gray-700 dark:text-slate-200 uppercase tracking-wider">
                Details
              </th>
            </tr>
          </thead>
          <tbody>
            {Object.entries(summary).map(([col, details], i) => (
              <tr 
                key={i} 
                className={`border-b border-gray-200 dark:border-slate-700 transition-colors hover:bg-blue-50 dark:hover:bg-slate-800 ${
                  i % 2 === 0 ? 'bg-white dark:bg-slate-900' : 'bg-gray-50 dark:bg-slate-900/50'
                }`}
              >
                <td className="px-6 py-4 text-sm font-semibold text-gray-800 dark:text-slate-200 align-top">
                  {col}
                </td>
                <td className="px-6 py-4 text-sm text-gray-600 dark:text-slate-300">
                  {details && typeof details === "object" && !Array.isArray(details) ? (
                    <table className="min-w-[300px] border border-gray-300 dark:border-slate-600 rounded-lg overflow-hidden shadow-sm">
                      <tbody>
                      {Object.entries(details).map(([k, v], j) => (
                        <tr 
                          key={j} 
                          className={`${
                            j % 2 === 0 
                                ? 'bg-gray-100 dark:bg-slate-800' 
                              : 'bg-white dark:bg-slate-900'
                            }`}
                          >
                            <td className="px-4 py-2 text-xs font-medium text-gray-700 dark:text-slate-200 border-r border-gray-300 dark:border-slate-600 uppercase tracking-wide">
                              {String(k)}
                            </td>
                            <td className="px-4 py-2 text-xs text-gray-900 dark:text-slate-100 font-mono">
                              {formatNumber(v)}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  ) : (
                    <span className="font-mono">{formatNumber(String(details))}</span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      
      {/* Info Banner */}
      <div className="p-5 bg-blue-50 dark:bg-blue-900/20 border-t border-blue-200 dark:border-blue-700">
        <p className="text-sm text-blue-800 dark:text-blue-300">
          <strong>💡 Tip:</strong> Click "Export PDF" to download a comprehensive report with statistical analysis and recommendations for forecasting.
        </p>
      </div>
    </div>
  );
}